import Head from "next/head";
import Image from "next/image";
import Banner from "../components/Banner";
import Card from "../components/Card";
import styles from "../styles/Home.module.css";
import { Fragment } from "react";
import response from "../data/response.json";

export async function getStaticProps(context) {
	return {
		props: { coffeeStores: response },
	};
}

const Home = ({ coffeeStores }) => {
	const handleOnBannerBtnClick = () => {
		console.log("Hi banner button");
	};

	console.log(coffeeStores);

	return (
		<div className={styles.container}>
			<Head>
				<title>Coffee Connoisseur</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<Banner
					buttonText="View stores nearby"
					handleOnClick={handleOnBannerBtnClick}
				/>
				<div className={styles.heroImage}>
					<Image
						src="/static/hero-image.png"
						width={700}
						height={400}
						alt="hero image"
						priority
					/>
				</div>
				{coffeeStores.length > 0 && (
					<Fragment>
						<h2 className={styles.heading2}>Toronto stores</h2>
						<div className={styles.cardLayout}>
							{coffeeStores.map((store) => (
								<Card
									key={store.fsq_id}
									name={store.name}
									imgUrl={
										store.imgUrl ||
										"https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"
									}
									href={`/coffee-store/${store.fsq_id}`}
									className={styles.card}
								/>
							))}
						</div>
					</Fragment>
				)}
			</main>
		</div>
	);
};

export default Home;
